CREATE DATABASE SEMSAL
GO
USE [SEMSAL]
CREATE TABLE ID (
	ID INT IDENTITY PRIMARY KEY,
	ID_AST INT
);
GO
USE [SEMSAL]
CREATE TABLE USERS (
	NOMBRE VARCHAR(20) PRIMARY KEY,
	PASS   VARCHAR(20),
	USUARIOS INT,
	SOMATOMETRIA INT,
	LABORATORIO INT,
	DENTAL INT,
	NUTRICION INT,
	MUJER INT,
	OPTOMETRIA INT,
	IMPRESION INT,
	EDITAR INT,
	IMPORTAR INT,
	EXPORTAR INT,
	FAMILIARES INT,
	ESTADISTICAS INT,
	AUDIOMETRIA INT,
	TUBERCULOSIS INT,
	CARDIOLOGIA INT
); 
GO

USE [SEMSAL]
INSERT INTO USERS(
	NOMBRE,
	PASS,
	USUARIOS,
	SOMATOMETRIA,
	LABORATORIO,
	DENTAL,
	NUTRICION,
	MUJER,
	OPTOMETRIA,
	IMPRESION,
	EDITAR,
	IMPORTAR,
	EXPORTAR,
	FAMILIARES,
	ESTADISTICAS,
	AUDIOMETRIA,
	TUBERCULOSIS,
	CARDIOLOGIA)
VALUES 
('Administrador',
'Administrator',
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1
);
GO
USE [SEMSAL]
CREATE TABLE SOMAT (
	ID_AST 	VARCHAR(10) PRIMARY KEY,
	NOMBRE 	VARCHAR(50),
	FE_NAC 	VARCHAR(10),
	EDAD	INT,
	GENERO 	VARCHAR(9),
	TRAB_E 	VARCHAR(2),
	AREA_T 	VARCHAR(50),
	ID_EMP 	VARCHAR(10),
	PARENT 	VARCHAR(10),
	PES_KG 	VARCHAR(6),
	TAL_MT 	VARCHAR(4),
	TA		VARCHAR(20),
	VAC_TX 	VARCHAR(2),
	VAC_OT 	VARCHAR(50),
	OBSERV	VARCHAR(50)
);
GO
USE [SEMSAL]
CREATE TABLE LABOR (
	ID_AST 	VARCHAR(10) PRIMARY KEY,
	COLEST 	INT,
	TRIGLI	INT,
	GLUCOS	INT,
	PSA		INT,
	OBSERV	VARCHAR(50)
);
GO
USE [SEMSAL]
CREATE TABLE DENTA (
	ID_AST 	VARCHAR(10) PRIMARY KEY,
	ASISTE	VARCHAR(2),
	OBSERV	VARCHAR(50)
);
GO
USE [SEMSAL]
CREATE TABLE NUTRI (
	ID_AST 	VARCHAR(10) PRIMARY KEY,
	ASISTE	VARCHAR(2),
	TIPO	VARCHAR(20),
	OBSERV	VARCHAR(50)
);
GO

USE [SEMSAL]
CREATE TABLE SD_MU (
	ID_AST 	VARCHAR(10) PRIMARY KEY,
	COCAMA	VARCHAR(2),
	COCCU	VARCHAR(2),
	MSTGFA	VARCHAR(2),
	OBSERV	VARCHAR(50)
);
GO
USE [SEMSAL]
CREATE TABLE OP_AD (
	ID_AST 	VARCHAR(10) PRIMARY KEY,
	OPTOME	VARCHAR(2),
	OBSERV	VARCHAR(50)
);
GO
USE [SEMSAL]
CREATE TABLE AUDIOM (
	ID_AST 	VARCHAR(10) PRIMARY KEY,
	ASISTE	VARCHAR(2),
	OBSERV	VARCHAR(50)
);
GO
USE [SEMSAL]
CREATE TABLE TUBER (
	ID_AST 	VARCHAR(10) PRIMARY KEY,
	ASISTE	VARCHAR(2),
	OBSERV	VARCHAR(50)
);
GO
USE [SEMSAL]
CREATE TABLE CARDIO (
	ID_AST 	VARCHAR(10) PRIMARY KEY,
	ASISTE	VARCHAR(2),
	OBSERV	VARCHAR(50)
);
SELECT ID_AST, ASISTE, OBSERV FROM CARDIO;
GO
USE [SEMSAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[All_date]
AS
SELECT  dbo.SOMAT.ID_AST, 
		dbo.SOMAT.NOMBRE, 
		dbo.SOMAT.FE_NAC AS FECHA_NACIMIENTO, 
		dbo.SOMAT.GENERO, 
		dbo.SOMAT.TRAB_E AS TRABAJADOR_EMPRESA, 
        dbo.SOMAT.AREA_T AS AREA_TRABAJO, 
		dbo.SOMAT.ID_EMP AS ID_PARIENTE, 
		dbo.SOMAT.PARENT AS RELACION, 
		dbo.SOMAT.PES_KG AS PESO, 
		dbo.SOMAT.TAL_MT AS TALLA, 
		dbo.SOMAT.TA, 
        dbo.SOMAT.VAC_TX AS VACUNA_TOXOIDE, 
		dbo.SOMAT.VAC_OT AS OTRAS_VACUNAS, 
		dbo.SOMAT.OBSERV AS OBSERVACIONES_SOMATOMETRÍA, 
		dbo.LABOR.COLEST AS COLESTEROL, 
		dbo.LABOR.TRIGLI AS TRIGLICERIDOS, 
		dbo.LABOR.GLUCOS AS GLUCOSA, 
        dbo.LABOR.PSA, 
		dbo.LABOR.OBSERV AS OBSERVACIONES_LABORATORIO,
		dbo.DENTA.ASISTE AS ASISTENCIA_DENTAL, 
        dbo.DENTA.OBSERV AS OBSERVACIONES_DENTAL,    
		dbo.NUTRI.ASISTE AS ASISTENCIA_NUTRICION, 
		dbo.NUTRI.TIPO, 
		dbo.NUTRI.OBSERV AS OBSERVACIONES_NUTRICION,
		dbo.SD_MU.COCAMA AS DOCMA, 
		dbo.SD_MU.COCCU AS DOCCU, 
		dbo.SD_MU.MSTGFA AS MASTOGRAFIA, 
        dbo.SD_MU.OBSERV AS OBSERVACIONES_SALUD_DE_LA_MUJER, 
		dbo.OP_AD.OPTOME AS OPTOMETRIA, 
        dbo.OP_AD.OBSERV AS OBSERVACIONES_OPTOMETRIA,
		dbo.AUDIOM.ASISTE AS ASISTENCIA_AUDIOMETRIA,
		dbo.AUDIOM.OBSERV AS OBSERVACIONES_AUDIOMETRIA,
		dbo.TUBER.ASISTE AS ASISTENCIA_TUBERCULOSIS,
		dbo.TUBER.OBSERV AS OBSERVACIONES_TUBERCULOSIS,
		dbo.CARDIO.ASISTE AS ASISTENCIA_CARDIOLOGIA,
		dbo.CARDIO.OBSERV AS OBSERVACIONES_CARDIOLOGIA
FROM    dbo.SOMAT FULL OUTER JOIN
        dbo.LABOR ON dbo.SOMAT.ID_AST = dbo.LABOR.ID_AST FULL OUTER JOIN
		dbo.DENTA ON dbo.SOMAT.ID_AST = dbo.DENTA.ID_AST FULL OUTER JOIN
        dbo.NUTRI ON dbo.SOMAT.ID_AST = dbo.NUTRI.ID_AST FULL OUTER JOIN
        dbo.SD_MU ON dbo.SOMAT.ID_AST = dbo.SD_MU.ID_AST FULL OUTER JOIN
        dbo.OP_AD ON dbo.SOMAT.ID_AST = dbo.OP_AD.ID_AST FULL OUTER JOIN
        dbo.AUDIOM ON dbo.SOMAT.ID_AST = dbo.AUDIOM.ID_AST FULL OUTER JOIN
        dbo.TUBER ON dbo.SOMAT.ID_AST = dbo.TUBER.ID_AST FULL OUTER JOIN
        dbo.CARDIO ON dbo.SOMAT.ID_AST = dbo.CARDIO.ID_AST;
GO
USE [SEMSAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V_DEN]
AS
SELECT 
	dbo.SOMAT.ID_AST,    
	dbo.SOMAT.NOMBRE, 
	dbo.SOMAT.EDAD, 
	dbo.SOMAT.GENERO, 
	dbo.SOMAT.TRAB_E, 
	dbo.DENTA.ASISTE
FROM         
	dbo.SOMAT INNER JOIN
    dbo.DENTA ON dbo.SOMAT.ID_AST = dbo.DENTA.ID_AST;
GO
USE [SEMSAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V_LAB]
AS
SELECT     
	dbo.SOMAT.ID_AST, 
	dbo.SOMAT.NOMBRE, 
	dbo.SOMAT.EDAD, 
	dbo.SOMAT.GENERO, 
	dbo.SOMAT.TRAB_E, 
	dbo.LABOR.COLEST, 
	dbo.LABOR.TRIGLI, 
	dbo.LABOR.GLUCOS, 
	dbo.LABOR.PSA
FROM         
	dbo.SOMAT INNER JOIN
    dbo.LABOR ON dbo.SOMAT.ID_AST = dbo.LABOR.ID_AST;
GO
USE [SEMSAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V_NUT]
AS
SELECT     
	dbo.SOMAT.ID_AST, 
	dbo.SOMAT.NOMBRE, 
	dbo.SOMAT.EDAD, 
	dbo.SOMAT.GENERO, 
	dbo.SOMAT.TRAB_E, 
	dbo.NUTRI.ASISTE
FROM         
	dbo.SOMAT INNER JOIN
    dbo.NUTRI ON dbo.SOMAT.ID_AST = dbo.NUTRI.ID_AST;
GO
USE [SEMSAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V_MUJ]
AS
SELECT     
	dbo.SOMAT.ID_AST, 
	dbo.SOMAT.NOMBRE, 
	dbo.SOMAT.EDAD, 
	dbo.SOMAT.GENERO, 
	dbo.SOMAT.TRAB_E, 
	dbo.SD_MU.COCAMA, 
	dbo.SD_MU.COCCU, 
	dbo.SD_MU.MSTGFA
FROM         
	dbo.SOMAT INNER JOIN
    dbo.SD_MU ON dbo.SOMAT.ID_AST = dbo.SD_MU.ID_AST;
GO
USE [SEMSAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V_OYA]
AS
SELECT     
	dbo.SOMAT.ID_AST, 
	dbo.SOMAT.NOMBRE, 
	dbo.SOMAT.EDAD, 
	dbo.SOMAT.GENERO, 
	dbo.SOMAT.TRAB_E, 
	dbo.OP_AD.OPTOME
FROM         
	dbo.SOMAT INNER JOIN
    dbo.OP_AD ON dbo.SOMAT.ID_AST = dbo.OP_AD.ID_AST;
GO
USE [SEMSAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V_AUD]
AS
SELECT     
	dbo.SOMAT.ID_AST, 
	dbo.SOMAT.NOMBRE, 
	dbo.SOMAT.EDAD, 
	dbo.SOMAT.GENERO, 
	dbo.SOMAT.TRAB_E, 
	dbo.AUDIOM.ASISTE
FROM         
	dbo.SOMAT INNER JOIN
    dbo.AUDIOM ON dbo.SOMAT.ID_AST = dbo.AUDIOM.ID_AST;
GO
USE [SEMSAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V_TUB]
AS
SELECT     
	dbo.SOMAT.ID_AST, 
	dbo.SOMAT.NOMBRE, 
	dbo.SOMAT.EDAD, 
	dbo.SOMAT.GENERO, 
	dbo.SOMAT.TRAB_E, 
	dbo.TUBER.ASISTE
FROM         
	dbo.SOMAT INNER JOIN
    dbo.TUBER ON dbo.SOMAT.ID_AST = dbo.TUBER.ID_AST;
GO
USE [SEMSAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V_CAR]
AS
SELECT     
	dbo.SOMAT.ID_AST, 
	dbo.SOMAT.NOMBRE, 
	dbo.SOMAT.EDAD, 
	dbo.SOMAT.GENERO, 
	dbo.SOMAT.TRAB_E, 
	dbo.CARDIO.ASISTE
FROM         
	dbo.SOMAT INNER JOIN
    dbo.CARDIO ON dbo.SOMAT.ID_AST = dbo.CARDIO.ID_AST;