CREATE DATABASE SOPORTE;

CREATE TABLE FONDO (
	ID INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	IMAGEN VARCHAR(500));

CREATE TABLE OBJETIVO (
	ID INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	TEXTO VARCHAR(5000));

CREATE TABLE MISION (
	ID INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	TEXTO VARCHAR(5000));

CREATE TABLE VISION (
	ID INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	TEXTO VARCHAR(5000));

CREATE TABLE RESENA (
	ID INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	TEXTO VARCHAR(5000));

CREATE TABLE REGISTRO (
	ID INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(100),
	FECHA VARCHAR (30));

CREATE TABLE SLASH (
	ID INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	IMAGEN VARCHAR(500),
	DESCRIPCION	VARCHAR(100));

CREATE TABLE COMUNICADOS (
	ID INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	TITULO VARCHAR(100),
	TEXTO VARCHAR(5000));

CREATE TABLE AGENDA (
	ID INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	AREA VARCHAR(100),
	PUESTO VARCHAR(100),
	NOMBRE VARCHAR(100),
	CORREO_INTERNO VARCHAR(100),
	CORREO_EXTERNO VARCHAR(100),
	CELULAR INT,
	EXTENSION INT,
	IMAGEN VARCHAR(500));

